name: Deploy

on:
  workflow_run:
    workflows: ["Building & Testing"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_URI: ${{secrets.REPO_URI}}
      ENV: ${{ secrets.ENV }}
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: ${{ secrets.HOST_PORT }}
        script: |
          sudo apt update
          sudo apt install -y nodejs
          sudo node -v
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update -y
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo docker -v
          sudo curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo docker-compose -v
          sudo mkdir -p uspect_test
          sudo cd uspect_test
          sudo rm -rf .git
          sudo git init
          sudo git remote add origin $REPO_URI
          sudo git clean -d -f || echo true
          sudo git pull origin main
          sudo echo $ENV | base64 -d > packages/server/.env
          sudo docker rmi $(docker images -f "dangling=true" -q) --force || true
          sudo docker-compose up -d --build
        envs: REPO_URI,ENV
        script_stop: true
        command_timeout: 6h
